language: node_js
node_js:
- 9.5.0
branches:
  only:
  - posts

install: npm install

before_script:
- git config --global user.name "Victor Jordan"
- git config --global user.email "victorjordan95@gmail.com"
- sed -i "s/__GITHUB_TOKEN__/${__GITHUB_TOKEN__}/" _config.yml
- npm install -g gulp

script: npm run build