# Header
menu:
  Home: /
rss: /atom.xml

# Content
excerpt_link: Ler mais
fancybox: true

# Sidebar
sidebar: right
widgets:
- category
- tag
- recent_posts

# display widgets at the bottom of index pages (pagination == 2)
index_widgets:
# - category
# - tagcloud
# - archive

# widget behavior
archive_type: 'monthly'
show_count: true

# Miscellaneous
google_analytics: UA-117244554-1
gauges_analytics:
favicon: /favicon.ico
twitter:
google_plus:
fb_admins:
fb_app_id:
